using System;
using System.Collections.Generic;
using System.IO;

namespace InspireStone
{
    class Act : Program
    {

        protected override void InspireSelect()
        {
            // (overridden from Program) prompts the user to select from a list of inspirations generated by _inspireList (if _step is greater than 4 and the _type is not pearl). Sets the selection as _select.
        }

        public void Acting()
        {
            // allows the user to act on selected inspiration.
        }

        public void Run()
        {
            // Implement behavior to bring up menu and initiate Act class
        }
    }
}