using System;
using System.Collections.Generic;
using System.IO;

namespace InspireStone
{
    class Plan : Program
    {
        private string frequent = "";
        private string period = "";

        protected override void InspireSelect()
        {
            // (overridden from Program) prompts the user to select from a list of inspirations generated by _inspireList (if _step is greater than 3 and the _type is not pearl). Sets the selection as _select.
        }

        public void Planit()
        {
            // prompts the user to plan to accomplish the inspiration.
        }

        public void Run()
        {
            // Implement behavior to bring up menu and initiate Plan class
        }
    }
}