using System;
using System.Collections.Generic;
using System.IO;

namespace InspireStone
{
    class Ponder : Program
    {
        private string refferal = "";
        private string text = "";

        protected override void InspireSelect()
        {
            // (overridden from Program) prompts the user to select from a list of inspirations generated by _inspireList (if _step is greater than 2). Sets the selection as _select.
        }

        public void Type()
        {
            // prompts user to choose the type from _typeList and sets it as _type.
        }

        public void Script()
        {
            // allows the user to copy and paste a scripture.
        }

        public void Run()
        {
            // Implement behavior to bring up menu and initiate Ponder class
        }
    }
}