using System;
using System.Collections.Generic;
using System.IO;

namespace InspireStone
{
    class Record : Program
    {

        private string journal = "";

        protected override void InspireSelect()
        {
            // (overridden from Program) prompts the user to select from a list of inspirations generated by _inspireList (if _step is greater than 6. Sets the selection as _select.

        }

        public void Recording()
        {
            // allows user to review everything about selected inspiration. And write a journal entry about it.
        }

        public void Run()
        {
            // Implement behavior to bring up menu and initiate Record class
        }
    }
}