using System;
using System.Collections.Generic;
using System.IO;

namespace InspireStone
{
    class Review : Program
    {

        protected override void InspireSelect()
        // (overridden from Program) prompts the user to select from a list of inspirations generated by _inspireList (if _step equals 6). Sets the selection as _select.
        {
            bool hasInspiration = false;

            // Check if there are any inspirations with step 6
            foreach (string inspire in _inspireList)
            {
                string[] parts = inspire.Split(new string[] { "///" }, StringSplitOptions.None);
                int step;
                if (Int32.TryParse(parts[0], out step))
                {
                    if (step == 6)
                    {
                        hasInspiration = true;
                        break;
                    }
                }
            }

            if (!hasInspiration)
            {
                Console.WriteLine("There are no inspirations to review.");
                Thread.Sleep(2000);
                return;
            }

            TypingEffect("\nSelect an inspiration to ponder:");
            Console.WriteLine();
            for (int i = 0; i < _inspireList.Count; i++)
            {
                string[] parts = _inspireList[i].Split(new string[] { "///" }, StringSplitOptions.None);
                int step;
                if (Int32.TryParse(parts[0], out step))
                {
                    if (step == 6)
                    {
                        Console.WriteLine($"{i + 1}. {parts[2]}");
                    }
                }
            }
            Console.WriteLine();
            BlinkIndicator();

            string input = Console.ReadLine();
            int selection;
            if (Int32.TryParse(input, out selection))
            {
                // Check if selection is within range
                bool isValidSelection = false;
                for (int i = 0; i < _inspireList.Count; i++)
                {
                    string[] parts = _inspireList[i].Split(new string[] { "///" }, StringSplitOptions.None);
                    int step;
                    if (Int32.TryParse(parts[0], out step))
                    {
                        if (step == 6 && selection == i + 1)
                        {
                            _index = i;
                            _select = _inspireList[_index];
                            Inspire.InspireSeperate();
                            TypingEffect($"Selected inspiration: {_name}");
                            Thread.Sleep(2000);
                            isValidSelection = true;
                            break;
                        }
                    }
                }
                if (!isValidSelection)
                {
                    Console.WriteLine("Invalid input, please try again.");
                }
            }
            else
            {
                Console.WriteLine("Invalid input, please try again.");
            }
        }

        public void Reviewed()
        {
            // Ask User if they have prayed and reviewed the Inspiration with the creator
            TypingEffect($"Have you prayed and reviewed the Inspiration '{_name}' with the Creator? (yes/no)");
            Console.WriteLine();
            BlinkIndicator();

            string answer = Console.ReadLine().ToLower();
            // if yes then:
            if (answer == "yes" || answer == "y" || answer == "Y")
            {
                _review = "Reviewed";
                StepUpgrade();
                Inspire.SaveInspiration();
                Inspire.AddLuminosity();
                Inspire.SaveInspireList();
            // if no then return
            }
            else if (answer == "no" || answer == "n" || answer == "N")
            {
                TypingEffect("OK, please try again later.");
                return;
                Thread.Sleep(2000);
                
            }
            else
            {
                Console.WriteLine("Invalid input. Please try again later.");
            }
        }

        public void Reviewing()
        {
            InspireSelect();
             if (_select == "") // check if no inspiration has been selected
            {
                return;
            }
            else
            {
                Inspire.DisplayInspiration();
                Console.ForegroundColor = ConsoleColor.DarkMagenta;
                Reviewed();
            }
        }

        protected override void Menu()
        {

            while (true)
            {   
                Console.Clear();
                // Display luminosity score
                Inspire.DisplayLuminosity();
                Console.WriteLine();
                Console.WriteLine("Select an option:");
                Console.WriteLine();
                Console.WriteLine("1. Review inspiration");
                Console.WriteLine("2. Return to Main Menu");
                Console.WriteLine();
                BlinkIndicator();

                string input = Console.ReadLine();
                int selection;
                if (Int32.TryParse(input, out selection))
                {
                    switch (selection)
                    {
                        case 1:
                            Reviewing();
                            if (_select == "") // check if no inspiration has been selected
                            {
                                return;
                            }
                            break;
                        case 2:
                            return;
                        default:
                            Console.WriteLine("Invalid input, please try again.");
                            break;
                    }
                }
                else
                {
                    Console.WriteLine("Invalid input, please try again.");
                }
            } 
        }

        public void Run()
        {
            // Implement behavior to bring up menu and initiate Review class
            Menu();
        }
    }
}